[project]
name = "content_creation_pipeline_v2"
version = "0.1.0"
description = "content_creation_pipeline___openai using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[litellm,tools]==1.8.0",
]

[project.scripts]
content_creation_pipeline___openai = "content_creation_pipeline___openai.main:run"
run_crew = "content_creation_pipeline___openai.main:run"
train = "content_creation_pipeline___openai.main:train"
replay = "content_creation_pipeline___openai.main:replay"
test = "content_creation_pipeline___openai.main:test"
run_with_trigger = "content_creation_pipeline___openai.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
